language: php

php:
 - 7.1
 - 7.2
 - 7.3
 - 7.4
 - 8.0

env: 
  - ILLUMINATE_VERSION=5.5.* 
  - ILLUMINATE_VERSION=5.6.* 
  - ILLUMINATE_VERSION=5.7.*  
  - ILLUMINATE_VERSION=5.8.* 
  - ILLUMINATE_VERSION=^6.0
  - ILLUMINATE_VERSION=^7.0

matrix:
  exclude:
    - php: 7.1
      env: ILLUMINATE_VERSION=^6.0
    - php: 7.1
      env: ILLUMINATE_VERSION=^7.0

before_install:
  - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
install:
 - composer update --no-interaction

script:
 - composer test