language: php

php:
 - 7.3
 - 7.4
 - 8.0

env: 
  - ILLUMINATE_VERSION=^8.0


before_install:
  - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
install:
 - composer update --no-interaction

script:
 - composer test